// Package output writes the user-facing results: per-country subscription
// files (subs/<CC>.txt) and a README.md summary table at the chosen output
// directory root.
//
// The format matches D-08 (README columns) and D-09 (subs files: plain
// vless:// URIs, one per line, UTF-8, LF endings).
package output

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/trikiman/vlessfilter/internal/selector"
)

// Write produces subs/<CC>.txt files and README.md inside outDir.
//
// outDir must exist. subs/ is created if missing.
func Write(outDir string, selections []selector.CountrySelection, generatedAt time.Time) error {
	subsDir := filepath.Join(outDir, "subs")
	if err := os.MkdirAll(subsDir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", subsDir, err)
	}

	for _, cs := range selections {
		path := filepath.Join(subsDir, cs.Country+".txt")
		var b strings.Builder
		for _, r := range cs.Top {
			b.WriteString(r.Link)
			b.WriteByte('\n')
		}
		if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}

	readme := buildReadme(selections, generatedAt)
	path := filepath.Join(outDir, "README.md")
	if err := os.WriteFile(path, []byte(readme), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// buildReadme renders the summary README.md. Format is locked by the
// golden-file test in this package.
func buildReadme(selections []selector.CountrySelection, generatedAt time.Time) string {
	var b strings.Builder

	stamp := generatedAt.UTC().Format(time.RFC3339)

	b.WriteString("# VlessFilter Results\n\n")
	b.WriteString("Auto-curated top 3 fastest VLESS keys per country, refreshed automatically.\n\n")
	fmt.Fprintf(&b, "**Last tested:** %s\n\n", stamp)
	b.WriteString("## How to use\n\n")
	b.WriteString("Pick a country below and paste the subscription URL into your VLESS client (Hiddify Next, v2rayN, Streisand, NekoBox, etc.):\n\n")
	b.WriteString("```\nhttps://raw.githubusercontent.com/trikiman/vlessfilter/main/subs/<CC>.txt\n```\n\n")
	b.WriteString("Replace `<CC>` with the 2-letter country code from the table.\n\n")
	b.WriteString("## Top 3 per country\n\n")
	b.WriteString("| Country | Top latency (ms) | Median speed (Mbps) | Keys | Last tested (UTC) |\n")
	b.WriteString("|---------|------------------|---------------------|------|-------------------|\n")

	// Sort countries alphabetically (Top3PerCountry already does this; defensive copy).
	rows := make([]selector.CountrySelection, len(selections))
	copy(rows, selections)
	sort.SliceStable(rows, func(i, j int) bool { return rows[i].Country < rows[j].Country })

	for _, cs := range rows {
		topLat := 0
		speeds := make([]float64, 0, len(cs.Top))
		for _, r := range cs.Top {
			if topLat == 0 || r.LatencyMs < topLat {
				topLat = r.LatencyMs
			}
			speeds = append(speeds, r.SpeedMbps)
		}
		fmt.Fprintf(&b, "| %s %s | %d | %.1f | %d | %s |\n",
			flagEmoji(cs.Country), cs.Country, topLat, median(speeds), len(cs.Top), stamp)
	}

	b.WriteString("\n_Generated by [vlessfilter](https://github.com/trikiman/vlessfilter). Source list: `sources.yaml`._\n")
	return b.String()
}

// flagEmoji converts a 2-letter ISO country code to its flag emoji.
// Each ASCII letter maps to its regional indicator symbol (codepoint
// 0x1F1A5 + letter). Returns the input unchanged on malformed inputs.
func flagEmoji(cc string) string {
	if len(cc) != 2 {
		return cc
	}
	a := cc[0]
	b := cc[1]
	if !(a >= 'A' && a <= 'Z') || !(b >= 'A' && b <= 'Z') {
		return cc
	}
	r1 := rune(a) + 0x1F1A5
	r2 := rune(b) + 0x1F1A5
	return string([]rune{r1, r2})
}

// median returns the median of a (possibly unsorted) slice, rounded to 1 decimal.
// Empty input returns 0.
func median(xs []float64) float64 {
	if len(xs) == 0 {
		return 0
	}
	sorted := make([]float64, len(xs))
	copy(sorted, xs)
	sort.Float64s(sorted)
	n := len(sorted)
	var m float64
	if n%2 == 1 {
		m = sorted[n/2]
	} else {
		m = (sorted[n/2-1] + sorted[n/2]) / 2
	}
	// Round to 1 decimal: shift, round, shift back
	rounded := float64(int64(m*10+0.5)) / 10
	return rounded
}
